NinetyNineCats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests
end

NinetyNineCats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NinetyNineCats/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = %w(red orange yellow blue)

  validates :birth_date, presence: true
  validates :color, inclusion: {in: COLORS}, presence: true
  validates :name, presence: true
  validates :sex, inclusion: {in: %w(M F)}, length: {is: 1}, presence: true

  has_many :cat_rental_requests,
  dependent: :destroy

  def age
    Time.now - birth_date
  end
end

NinetyNineCats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  statuses = %w(PENDING APPROVED DENIED)
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: statuses }, presence: true
  validates :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    self.class
      .where(cat_id: cat_id)
      .where.not(id: id)
      .where("(self.start_date BETWEEN start_date AND end_date) OR
      (self.end_date BETWEEN start_date AND end_date)")
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:request] << "Can't overlapping booking with approved requests"
    end
  end
end

NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

NinetyNineCats/app/controllers/cat_requests_controller.rb
class CatRequestsController < ApplicationController
end

NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def show
    @cat = selected_cat
    if @cat
      render :show
    else
      render 'Cat does not exist', status: 400
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render 'Invalid', status: 400
    end
  end

  def edit
    @cat = selected_cat
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 400
    end
  end

  private
  def selected_cat
    Cat.find_by(id: params[:id])
  end

  def cat_params
    params.require(:cat).permit(:sex, :birth_date, :color, :description, :name)
  end
end

NinetyNineCats/app/helpers/application_helper.rb
module ApplicationHelper
end

NinetyNineCats/app/helpers/cat_requests_helper.rb
module CatRequestsHelper
end

NinetyNineCats/app/helpers/cats_helper.rb
module CatsHelper
end

NinetyNineCats/app/views/cats/_cat.html.erb
<%= link_to cat.name, cat_url(cat) %> -
<%= cat.sex %>
<%= cat.birth_date %>
<%= cat.color %>
<%= cat.description %>

NinetyNineCats/app/views/cats/_form.html.erb
<% _action = cat.id ? cat_url(cat) : cats_url %>
<% _verb = cat.id ? "PATCH" : "POST" %>


<form action="<%= _action %>" method="post">
  <input type="hidden" name="_method" value="<%= _verb %>">
      <label>
        <strong>Name:</strong>
        <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
      </label>
      <br>
      <label>
        <strong>Sex:</strong>
          <input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>> Male
          <input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>> Female
      </label>
      <label>
        <strong>Birthday:</strong>
        <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
      </label>
      <br>
      <label>
        <strong>Color:</strong>
        <select name="cat[color]" value ="<%= cat.color %>">
          <option selected disabled hidden>Choose here</option>
          <option  <%= cat.color == "red" ? "selected" : "" %> value = "red">Red</option>
          <option  <%= cat.color == "orange" ? "selected" : "" %> value = "orange">Orange</option>
          <option  <%= cat.color == "yellow" ? "selected" : "" %> value = "yellow">Yellow</option>
          <option  <%= cat.color == "blue" ? "selected" : "" %> value = "blue">Blue</option>
        </select>
      </label>
      <br>
      <label>
        <strong>Description:</strong>
        <textarea name="cat[description]">
          <%= cat.description %>
        </textarea>
      </label>

      <br>
      <input type="submit"/>
  </form>

NinetyNineCats/app/views/cats/edit.html.erb
<h1>Edit information </h1>

<%= render "form", cat: @cat %>

NinetyNineCats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<%= link_to "Create cat", new_cat_url %>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= render 'cat', cat: cat %>
    </li>
  <% end %>
</ul>

NinetyNineCats/app/views/cats/new.html.erb
<h1> Aww, new cat was born! Enter his/her information </h1>

<%= render "form", cat: @cat %>

NinetyNineCats/app/views/cats/show.html.erb
<h1><%= @cat.name %>'s Information</h1>

<%= link_to "All Cats", cats_url %>
<%= link_to "Edit Cat", edit_cat_url(@cat) %>
<table>
  <th> <%= @cat.name %>  </th>
  <tr>
    <td> Sex: </td>
    <td> <%= @cat.sex %> </td>
  </tr>
  <tr>
    <td> Birthdate: </td>
    <td><%= @cat.birth_date %> </td>
  </tr>
  <tr>
    <td> Color: </td>
    <td> <%= @cat.color %></td>
  </tr>
  <tr>
    <td> Description: </td>
    <td><%= @cat.description %> </td>
  </tr>
</table>

NinetyNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>